export const itemsDummyData = [
  {
    id: "1",
    image: require("../assets/images/clothes/black-tshirt.png"),
    brand: "H&M",
    name: "Black T-Shirt",
  },
  {
    id: "2",
    image: require("../assets/images/clothes/grayPants.webp"),
    brand: "pull & bear",
    name: "Green Pants",
  },
  {
    id: "3",
    image: require("../assets/images/clothes/green-converse.png"),
    brand: "Converse",
    name: "Green Converse",
  },
  {
    id: "4",
    image: require("../assets/images/clothes/beanie.png"),
    brand: "pull & bear",
    name: "Black Beanie",
  },
  {
    id: "5",
    image: require("../assets/images/clothes/sunglasses.png"),
    brand: "Louis Vuitton",
    name: "Sunglasses",
  },
  {
    id: "6",
    image: require("../assets/images/clothes/plaid-shirt.png"),
    brand: "pull & bear",
    name: "Red Plaid Shirt",
  },
  {
    id: "7",
    image: require("../assets/images/clothes/olivegreen-pants.png"),
    brand: "pull & bear",
    name: "Gray Sweatpants",
  },
];

export const outfitsDummyData = [
  {
    outfitId: "101",
    recent: true,
    favorites: false,
    items: [
      {
        id: "1",
        image: require("../assets/images/clothes/blackHoodie.png"),
        brand: "H&M",
        name: "Black T-Shirt",
        color: "#000",
      },
      {
        id: "3",
        image: require("../assets/images/clothes/jordans.png"),
        brand: "Nike",
        name: "Black Air Jordan",
        color: "#FFF",
      },
      {
        id: "2",
        image: require("../assets/images/clothes/grayPants.webp"),
        brand: "pull & bear",
        name: "Green Pants",
        color: "#878787",
      },
      {
        id: "5",
        image: require("../assets/images/clothes/sunglasses.png"),
        brand: "Louis Vuitton",
        name: "Sunglasses",
      },
    ],
  },
  {
    outfitId: "102",
    recent: true,
    favorites: true,

    items: [
      {
        id: "1",
        image: require("../assets/images/clothes/whiteHoodie.png"),
        brand: "H&M",
        name: "Black T-Shirt",
        color: "#FFF",
      },
      {
        id: "3",
        image: require("../assets/images/clothes/jordans.png"),
        brand: "Nike",
        name: "Black Air Jordan",
        color: "#FFF",
      },
      {
        id: "2",
        image: require("../assets/images/clothes/blackPants.png"),
        brand: "pull & bear",
        name: "Green Pants",
        color: "#000",
      },
      {
        id: "5",
        image: require("../assets/images/clothes/sunglasses.png"),
        brand: "Louis Vuitton",
        name: "Sunglasses",
      },
    ],
  },
  {
    outfitId: "103",
    recent: false,
    favorites: true,
    items: [
      {
        id: "1",
        image: require("../assets/images/clothes/orangeShirt.png"),
        brand: "H&M",
        name: "Black T-Shirt",
        color: "#DB5616",
      },
      {
        id: "3",
        image: require("../assets/images/clothes/redJordans.png"),
        brand: "Nike",
        name: "Black Air Jordan",
        color: "#DB5616",
      },
      {
        id: "2",
        image: require("../assets/images/clothes/blackPants.png"),
        brand: "pull & bear",
        name: "Green Pants",
        color: "#000",
      },
      {
        id: "5",
        image: require("../assets/images/clothes/sunglasses.png"),
        brand: "Louis Vuitton",
        name: "Sunglasses",
      },
    ],
  },
  {
    outfitId: "104",
    recent: true,
    favorites: false,
    items: [
      {
        id: "1",
        image: require("../assets/images/clothes/black-tshirt/black-tshirt.png"),
        brand: "H&M",
        name: "Black T-Shirt",
      },
      {
        id: "3",
        image: require("../assets/images/clothes/blueJordans.png"),
        brand: "Nike",
        name: "Black Air Jordan",
      },
      {
        id: "2",
        image: require("../assets/images/clothes/grayPants.webp"),
        brand: "pull & bear",
        name: "Gray Pants",
      },
      {
        id: "5",
        image: require("../assets/images/clothes/sunglasses.png"),
        brand: "Louis Vuitton",
        name: "Sunglasses",
      },
    ],
  },
  {
    outfitId: "105",
    recent: false,
    favorites: false,
    items: [
      {
        id: "1",
        image: require("../assets/images/clothes/blueShirt.png"),
        brand: "H&M",
        name: "Black T-Shirt",
      },
      {
        id: "3",
        image: require("../assets/images/clothes/blueJordans.png"),
        brand: "Nike",
        name: "Black Air Jordan",
      },
      {
        id: "2",
        image: require("../assets/images/clothes/blackPants.png"),
        brand: "pull & bear",
        name: "Green Pants",
      },
      {
        id: "5",
        image: require("../assets/images/clothes/sunglasses.png"),
        brand: "Louis Vuitton",
        name: "Sunglasses",
      },
    ],
  },
  {
    outfitId: "106",
    recent: false,
    favorites: false,
    items: [
      {
        id: "1",
        image: require("../assets/images/clothes/whiteHoodie.png"),
        brand: "H&M",
        name: "Black T-Shirt",
      },
      {
        id: "3",
        image: require("../assets/images/clothes/redJordans.png"),
        brand: "Nike",
        name: "Black Air Jordan",
      },
      {
        id: "2",
        image: require("../assets/images/clothes/brownPants.png"),
        brand: "pull & bear",
        name: "Green Pants",
      },
      {
        id: "5",
        image: require("../assets/images/clothes/sunglasses.png"),
        brand: "Louis Vuitton",
        name: "Sunglasses",
      },
    ],
  },
  {
    outfitId: "107",
    recent: false,
    favorites: false,
    items: [
      {
        id: "1",
        image: require("../assets/images/clothes/black-tshirt/black-tshirt.png"),
        brand: "H&M",
        name: "Black T-Shirt",
      },
      {
        id: "3",
        image: require("../assets/images/clothes/jordans.png"),
        brand: "Nike",
        name: "Black Air Jordan",
      },
      {
        id: "2",
        image: require("../assets/images/clothes/grayPants.webp"),
        brand: "pull & bear",
        name: "Green Pants",
      },
      {
        id: "5",
        image: require("../assets/images/clothes/sunglasses.png"),
        brand: "Louis Vuitton",
        name: "Sunglasses",
      },
    ],
  },
];

export const filtersData = [
  {
    id: 1,
    filterGroup: "Occasion",
    options: ["Casual", "Formal", "Semi-Formal", "Sport"],
  },
  {
    id: 2,
    filterGroup: "style",
    options: ["Oversize", "Slim Fit", "Old Money", "Streetwear"],
  },
  {
    id: 3,
    filterGroup: "Category",
    options: [
      "Topwear",
      "Bottomwear",
      "Watches",
      "Socks",
      "Shoes",
      "Belts",
      "Flip Flops",
      "Bags",
      "Sandal",
      "Eyewear",
      "Jewellery",
      "Scarves",
      "Dress",
      "Wallets",
      "Headwear",
      "Ties",
    ],
  },
  {
    id: 4,
    filterGroup: "Color",
    options: [
      "Black",
      "White",
      "Blue",
      "Red",
      "Green",
      "Beige",
      "Gray",
      "Orange",
    ],
  },
  {
    id: 5,
    filterGroup: "Season",
    options: ["Winter", "Spring", "Summer", "Fall"],
  },
];

export const generationTags = [
  {
    id: 11,
    filterGroup: "dressCode",
    options: ["Casual", "Formal", "Semi-Formal", "Sport"],
  },
  {
    id: 12,
    filterGroup: "style",
    options: ["Oversize", "Slim Fit", "Old Money", "Streetwear"],
  },
  {
    id: 13,
    filterGroup: "theme",
    options: [
      "Skin",
      "Sunset",
      "Winter",
      "Christmas",
      "Sea",
      "Summer",
      "Retro",
      "Kids",
      "Pastel",
      "Gold",
      "Light",
      "Rainbow",
      "Wedding",
      "Food",
      "Happy",
      "Neon",
      "Spring",
      "Earth",
      "Sky",
      "Space",
      "Nature",
      "Warm",
      "Dark",
      "Halloween",
      "Popular",
      "Gradient",
      "Cream",
      "Coffee",
      "Fall",
      "Night",
      "Cold",
      "New",
    ],
  },
  {
    id: 14,
    filterGroup: "weather",
    options: ["Spring", "Fall", "Summer", "Winter"],
  },
];
